apiVersion: v1
kind: Namespace
metadata:
  name: image-clone-controller
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: image-clone-controller-manager
  name: image-clone-controller-manager
  namespace: image-clone-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-clone-controller-imanager
  template:
    metadata:
      labels:
        app: image-clone-controller-imanager
    spec:
      serviceAccount: image-clone-controller
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: repo.treescale.com/kmjayadeep/image-clone-controller:latest
        name: image-clone-controller
        imagePullPolicy: Always
