apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-clone-controller
  namespace: image-clone-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-clone-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-clone-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-clone-role
subjects:
- kind: ServiceAccount
  name: image-clone-controller
  namespace: image-clone-controller

